#!/bin/bash

help() {
  echo "Bootstrap - setup environment quickly"
  echo ""
  echo "Usage:"
  echo "  ta bootstrap [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::bootstrap
}

run() {
  core $@
}

run $@
