#!/bin/bash

help() {
  echo "Build - ta build"
  echo ""
  echo "Usage:"
  echo "  ta build [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)] start to build ta ..."

  ta::build

  log::info "[$(timestamp)] succeed to build ta."
}

run() {
  core $@
}

run $@
