#!/bin/bash

help() {
  echo "Build - ta build"
  echo ""
  echo "Usage:"
  echo "  ta build [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)] start to build ta ..."

  which node >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] node.js is not installed, try to install it ..."
    zmicro package install nodejs

    export NODE_HOME=/usr/local/node
    export NODE_USER_HOME=$HOME/.node
    export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH
  fi

  npm run build
  if [ $? -ne 0 ]; then
    log::error "[$(timestamp)] failed to build: npm run build failed"
    exit 1
  fi

  npm run dist --if-present
  if [ $? -ne 0 ]; then
    log::error "[$(timestamp)] failed to build: npm run dist failed"
    exit 1
  fi

  log::info "[$(timestamp)] succeed to build ta."
}

run() {
  core $@
}

run $@
