#!/bin/bash

help() {
  echo "Commit - ta commit"
  echo ""
  echo "Usage:"
  echo "  ta commit"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta:commit
}

run() {
  core $@
}

run $@
