#!/bin/bash

help() {
  echo "Commit - ta commit"
  echo ""
  echo "Usage:"
  echo "  ta commit [options...]"
  echo ""
  echo "Options:"
  echo "    --no-push   Don't push the commit to remote"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta:commit "$@"
}

run() {
  core "$@"
}

run "$@"
