#!/bin/bash

help() {
  echo "Dev - ta dev"
  echo ""
  echo "Usage:"
  echo "  ta dev [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::dev
}

run() {
  core $@
}

run $@
