#!/bin/bash

help() {
  echo "Dev - ta dev"
  echo ""
  echo "Usage:"
  echo "  ta dev [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  # 给 dev 添加参数，可以运行不同的环境
  if  [ "$1" = "ta" ] || [ "$1" = "va" ] || [ "$1" = "hermes" ] || [ "$1" = "h5" ] || [ "$1" = "sso" ];  then
    ta::dev $1
    exit 0
  else 
    ta::dev
  fi
}

run() {
  core $@
}

run $@
