#!/bin/bash

help() {
  echo "Fmt - ta fmt"
  echo ""
  echo "Usage:"
  echo "  ta fmt"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::fmt
}

run() {
  core $@
}

run $@
