#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_TA_NAME)
  echo "Ta ($(color::success $version))"
}

description() {
  # @TODO
  config::load_file $PLUGIN_DIR/mod

  echo "$PLUGIN_DESCRIPTION"
}

usage() {
  echo "Usage: ta <command> [args...]"
  echo ""
  echo "Commands:"
  echo "  环境相关"
  echo "  setup               - Setup Ta Development Environment"
  echo ""
  echo "  项目管理"
  echo "  add <repository>    - Add Git Repository"
  echo ""
  echo "  日常开发"
  echo "  bootstrap           - Bootstrap project"
  echo "  dev                 - Project dev"
  echo "  commit              - Project commit"
  echo "  fmt                 - Project format"
  echo ""
  echo "  分支管理"
  echo "  feat                - Create feature branch"
  echo "  branch <type>       - Create branch by feat/fix/hotfix/release"
  echo "  mr                  - Create merge request (:WIP:)"
  echo ""
  echo "  构建部署"
  echo "  build               - Project build"
  echo ""
  echo "  其他扩展"
  echo "  run                 - Run npm script"
  echo ""
  echo "  配置管理"
  echo "  config              - Get/set config"
  echo ""
  echo "  系统相关"
  echo "  info                - Show system info"
  echo "  update              - Update CLI"
  echo "  version             - Show version"
  echo "  help                - Show help"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
}

run() {
  core $@
}

run $@
