#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_TA_NAME)
  echo "Ta ($(color::success $version))"
}

description() {
  # @TODO
  config::load_file $PLUGIN_DIR/mod

  echo "$PLUGIN_DESCRIPTION"
}

usage() {
  echo "Usage:"
  echo "  ta setup               - Setup Ta Development Environment"
  echo "  ta add <repository>    - Add Git Repository"
  echo "  ta bootstrap           - Bootstrap project"
  echo "  ta dev                 - Project dev"
  echo "  ta build               - Project build"
  echo "  ta fmt                 - Project format"
  echo "  ta commit              - Project commit"
  echo "  ta run                 - Run npm script"
  echo "  ta config              - Get/set ta config"
  echo "  ta version             - Show version"
  echo "  ta update              - Show update"
  echo "  ta info                - Show system info"
  echo "  ta help                - Show help"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
}

run() {
  core $@
}

run $@
