#!/bin/bash

help() {
  echo "Create a new bugfix branch"
  echo ""
  echo "Usage:"
  echo "  ta branch fix [version] [function]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::hostname
}

run() {
  core $@
}

run $@
