#!/bin/bash

help() {
  echo "Info - ta info"
  echo ""
  echo "Usage:"
  echo "  ta info [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::info
}

run() {
  core $@
}

run $@
