#!/bin/bash

help() {
  echo "Intl - ta intl"
  echo ""
  echo "Usage:"
  echo "  ta intl [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)] start to intl ta ..."

  ta::intl

  log::info "[$(timestamp)] succeed to intl ta."
}

run() {
  core $@
}

run $@
