#!/bin/bash

help() {
  echo "Push - ta push"
  echo ""
  echo "Usage:"
  echo "  ta push [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::push
}

run() {
  core $@
}

run $@
