#!/bin/bash

help() {
  echo "Setup - setup environment"
  echo ""
  echo "Usage:"
  echo "  ta setup [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::setup
}

run() {
  core $@
}

run $@
