#!/bin/bash

ta::bootstrap() {
  ta::prepare

  local package_json=$PWD/package.json

  # COMMAND from .tarc
  local bootstrap_command=$(ta::config BOOTSTRAP_COMMAND)
  if [ -n "$bootstrap_command" ]; then
    eval "$bootstrap_command"
    return
  fi

  # COMMAND from package.json
  if [ -f "$package_json" ]; then
    npm run clear --if-present

    if [ "$CI" = "true" ]; then
      npm ci --legacy-peer-deps
    else
      npm i --legacy-peer-deps
    fi
    
    return
  fi

  # ERROR: NO COMMAND FOUND
  log::error "[$(timestamp)] failed to bootstrap, no logic found"
}

export -f ta::bootstrap
