#!/bin/bash

ta::config() {
  # ta::prepare

  local key=$1
  local value=$2
  local opt=$3

  if [ "$key" = "" ]; then
    echo -e "=== Global Config ===\n"
    if [ -f "$PLUGIN_TA_GLOBAL_RC" ]; then
      echo -e "$(fs::read $PLUGIN_TA_GLOBAL_RC)\n\n"
    fi
    echo -e "=== Local Config ===\n"
    if [ -f "$PLUGIN_TA_LOCAL_RC" ]; then
      echo -e "$(fs::read $PLUGIN_TA_LOCAL_RC)\n\n"
    fi
    return 0
  fi

  if [ "$value" = "" ]; then
    local val=""

    if [ -f "$PLUGIN_TA_LOCAL_RC" ]; then
      val=$(config::get $key $PLUGIN_TA_LOCAL_RC)
    fi

    if [ "$val" = "" ]; then
      if [ -f "$PLUGIN_TA_GLOBAL_RC" ]; then
        val=$(config::get $key $PLUGIN_TA_GLOBAL_RC)
      fi
    fi

    if [ "$val" = "" ]; then
      echo ""
      return 1
    fi

    echo "$val"
    return 0
  fi

  if [ "$opt" = "-g" ]; then
    if [ ! -f "$PLUGIN_TA_GLOBAL_RC" ]; then
      echo "" >>$PLUGIN_TA_GLOBAL_RC
    fi
    # @TODO gpm
    if [ "$key" = "project.workdir" ]; then
      if [ -z "$value" ]; then
        log::error "workdir is required, but empty"
        return 1
      fi

      local gpm_version="v$(gpm --version)"
      if [ "$(semver::compare_gte ${gpm_version} v1.4.3)" != "true" ]; then
        log::info "[$(timestamp)] config project.workdir need gpm(v1.4.3) or higher version"
        npm i -g @cliz/gpm # @$PLUGIN_TA_GPM_VERSION --force
      fi

      gpm config set project.workdir $value
      return 0
    fi

    config::set $key $value $PLUGIN_TA_GLOBAL_RC
    log::info "Set Global Config"
    log::info "$key: $(color::green $value)"
    return 0
  fi

  if [ ! -f "$PLUGIN_TA_LOCAL_RC" ]; then
    echo "" >>$PLUGIN_TA_LOCAL_RC
  fi
  config::set $key $value $PLUGIN_TA_LOCAL_RC
  log::info "Set Local Config"
  log::info "$key: $(color::green $value)"
}

export -f ta::config
