#!/bin/bash

ta::debug() {
  which eunomia-runner-unicom >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] debug tool is not installed, try to install it ..."
    zmicro package install eunomia-runner-unicom
  fi

  # check version
  local latest_version=$(curl -s http://10.27.249.150:8888/eunomia/shared/raw/master/eunomia-runner-unicom/version)
  local current_version=$(eunomia-runner-unicom --version)
  if [ "$current_version" != "$latest_version" ]; then
    log::info "[$(timestamp)] debug tool is outdated, try to update it ..."
    zmicro package install eunomia-runner-unicom
  fi

  local frontend=""
  local frontend_oauth=""
  # common service default port: 8992
  local backend="http://127.0.0.1:8992"

  while [ $# -gt 0 ]; do
    case $1 in
    --docker | --frontend)
      frontend=$2
      shift 2
      ;;
    --frontend-oauth)
      frontend_oauth=$2
      shift 2
      ;;
    --api | --backend)
      backend=$2
      shift 2
      ;;
    *)
      log::error "unknown option $1"
      exit 1
      ;;
    esac
  done

  if [ "$frontend" = "" ]; then
    log::error "docker url is required, please use --docker <url>"
    exit 1
  fi

  if [ "$frontend_oauth" = "" ]; then
    frontend_oauth=$frontend
  fi

  log::info "##################################"
  log::info "#           TA DEBUG             #"
  log::info "##################################"
  log::info "######## DEBUG INFO START ########"
  log::info "# frontend: $frontend"
  log::info "# frontend_oauth: $frontend_oauth"
  log::info "# backend: $backend"
  log::info "######## DEBUG INFO END ########"
  echo ""

  ta::debug_open_browser >/dev/null &

  eunomia-runner-unicom dev --frontend $frontend --backend $backend --frontend-oauth $frontend_oauth
}

ta::debug_open_browser() {
  local url="http://127.0.0.1:9000"

  sleep 1

  os::open $url
}

export -f ta::debug
export -f ta::debug_open_browser
