#!/bin/bash

ta::dev() {
  ta::prepare

  local package_json=$PWD/package.json

  # COMMAND from .tarc
  local custom_command=$(ta::config "DEV_COMMAND")
  if [ -n "$custom_command" ]; then
    eval "$custom_command"
    return
  fi

  local key="DEV_SCRIPT"
  local npm_command=$(ta::config ${key})

  # COMMAND from package.json
  if [ -f "$package_json" ]; then
    if [ "$npm_command" = "" ]; then
      npm run dev --if-present
      npm run start --if-present
    else
      npm run "$npm_command"
    fi
    return
  fi

  # ERROR: NO COMMAND FOUND
  log::error "[$(timestamp)] 当前目录不是有效目录，请在仓库目录中执行该命令"
  return 1
}

export -f ta::dev
