#!/bin/bash

ta::dev() {
  ta::prepare

  # 给 dev 添加参数，可以运行不同的环境
  local dev_env="$1"

  # 修复 4.0 openssl bug
  export NODE_OPTIONS="--openssl-legacy-provider"

  # 修复 nx daemon process terminated and closed the connection
  #   https://github.com/nrwl/nx/issues/12237
  #   https://nx.dev/more-concepts/nx-daemon#turning-it-off
  # 
  # export WEBPACK_FS_CACHE="none"
  export NX_DAEMON=false
  # END

  local package_json=$PWD/package.json

  # COMMAND from .tarc
  local custom_command=$(ta::config "DEV_COMMAND")
  if [ -n "$custom_command" ]; then
    eval "$custom_command"
    return
  fi

  local key="DEV_SCRIPT"
  local npm_command=$(ta::config ${key})

  # COMMAND from package.json
  if [ -f "$package_json" ]; then
    # handle ta-proxy not terminated correctly
    if [ "$NO_TA_PROXY" = "" ]; then
      nc -z -v -n 127.0.0.1 10010 >>/dev/null 2>&1
      if [ "$?" = "0" ]; then
        kill -9 $(lsof -t -i:10010)
      fi
    fi

    if [ "$npm_command" = "" ]; then
      # 如果有 dev_env 参数，则启动对应环境
      if [ "$dev_env" != "" ]; then
        echo "[$(timestamp)] 开始启动 $dev_env 环境 ..."
        npm run start:$dev_env --if-present
      else 
        npm run dev --if-present
        npm run start --if-present
      fi
    else
      npm run "$npm_command"
    fi
    return
  fi

  # not a git repository
  if [ ! -d "$PWD/.git" ]; then
    log::error "[$(timestamp)] 当前目录不是有效目录，请在仓库目录中执行该命令"
    return 1
  fi

  # ERROR: NO COMMAND FOUND
  log::error "[$(timestamp)] failed to dev, no logic found"
  return 1
}

export -f ta::dev
