#!/bin/bash

ta::info() {
  ta::prepare

  log::info "node: $(color::green $(node -v)) ($(which node))"
  log::info "npm: $(color::green v$(npm -v)) ($(which npm))"

  if [ "$(os::has_command yarn)" = "true" ]; then
    log::info "yarn: $(color::green v$(yarn -v))"
  fi

  if [ "$(os::has_command pnpm)" = "true" ]; then
    log::info "pnpm: $(color::green v$(pnpm -v))"
  fi

  log::info "gpm: $(color::green v$(gpm --version))"
  log::info "nvm: $(nvm -v)"
  log::info "ta: $(ta version)"
  log::info "zmicro: $(zmicro version)"
  log::info "os:"
  log::info "  release: $(os::release)"
  log::info "  arch: $(os::arch)"
  log::info "  kernel: $(os::kernel)"
  log::info "  platform: $(os::platform)"
  log::info "  device: $(os::device_config)"

}

export -f ta::info
