#!/bin/bash

ta::intl() {
  ta::prepare

  local intl_config=$PWD/intl.json
  if [ ! -f "$intl_config" ]; then
    log::info "[$(timestamp)] ignore intl by not found intl config: $intl_config"
    exit 0
  fi

  log::info "[$(timestamp)] start to intl ..."
  npx tant-intl build
  if [ $? -ne 0 ]; then
    log::error "[$(timestamp)] failed to intl: npx tant-intl build failed"
    exit 1
  fi

  log::info "[$(timestamp)] succeed to intl."
}

export -f ta::intl
