#!/bin/bash

ta::intl_build() {
  ta::prepare

  local intl_config=$PWD/intl.json
  if [ ! -f "$intl_config" ]; then
    log::info "[$(timestamp)] ignore intl by not found intl config: $intl_config"
    return 1 0
  fi

  npx tant-intl build
  if [ $? -ne 0 ]; then
    return 1
  fi
}

export -f ta::intl_build
