#!/bin/bash

ta::mr() {
  local current_branch_name=$(git::branch)

  # 检查repo是不是ta repo
  local git_repo_url=$(git::repo_url)
  # http://10.27.249.150:8888/thinking-frontend/ta-multiverse
  # http://10.27.249.150:8888/thinking-frontend/ta-multiverse.git
  # ssh://git@139.224.169.199:26662/thinking-frontend/ta-multiverse.git

  local check_http_url=$(echo $git_repo_url | awk -F '10.27.249.150:8888/' '{print $2}')
  local check_ssh_url=$(echo $git_repo_url | awk -F '139.224.169.199:26662/' '{print $2}')
  if [ "$check_http_url" = "" ] && [ "$check_ssh_url" = "" ]; then
    log::info "❤️暂不支持非ta项目❤️"
    return 1
  fi

  # 获得repo的group和projectName
  local git_repo_group=$(git::namespace)
  local git_repo_project=$(git::basename)
  local repo_name="$git_repo_project"
  if [ "$git_repo_group" != "" ]; then
    repo_name="${git_repo_group}%2F${git_repo_project}"
  fi

  # 设置gitlab key
  local key="GITLAB_TOKEN"
  local gitlab_token=$(ta::config ${key})
  if [ "$gitlab_token" = "" ]; then
    log::info "没有发现gitlab token，请打开下面链接获取token"
    log::info "http://10.27.249.150:8888/profile/personal_access_tokens"
    os::inquirer gitlab_token "text" "请输入gitlab token" true
    ta::config $key "$gitlab_token" -g

    # gitlab_token=$(git::get_token "10.27.249.150")
  fi

  # if [ "$gitlab_token" = "" ]; then
  #   # update git config
  #   zmicro config git

  #   # auto login without create token on gitlab
  #   log::info "[$(timestamp)] you are loginning gitlab ..."
  #   git clone --depth 1 http://10.27.249.150:8888/thinking-frontend/ta-multiverse /tmp/for_login
  #   gitlab_token=$(git::get_token "10.27.249.150")
  #   if [ -z "$gitlab_token" ]; then
  #     log::info "没有发现gitlab token，请打开下面链接获取token"
  #     log::info "http://10.27.249.150:8888/profile/personal_access_tokens"
  #     os::inquirer gitlab_token "text" "请输入gitlab token" true
  #     ta::config $key "$gitlab_token" -g
  #   fi
  # fi

  # 设置target branch
  local type=$(echo $current_branch_name | awk -F '/' '{print $1}')
  local target_branch_name="sprint_dev"
  if [ "$type" = "hotfix" ]; then
    local branch=$(echo $current_branch_name | awk -F '/' '{print $2}')
    local version=$(echo $branch | awk -F '_' '{print $1}')
    target_branch_name="release/${version}"
  fi
  if [ "$type" != "feature" ] && [ "$type" != "fix" ] && [ "$type" != "hotfix" ]; then
    os::inquirer target_branch_name "text" "请输入目标分支" true
  else
    os::inquirer value "text" "请输入目标分支" true ${target_branch_name}
    if [ "$value" != "" ]; then
      target_branch_name="${value}"
    fi
  fi

  # 设置请求体
  local tmp_data_file=$(os::tmp_file)
  cat <<-END >$tmp_data_file
{
  "target_branch": "${target_branch_name}",
  "source_branch": "${current_branch_name}",
  "title": "${current_branch_name}",
  "assignee_id": "13",
  "remove_source_branch": true,
  "squash": true
}
END

  # 发送mr请求
  local mr_result=$(curl --request POST -H "PRIVATE-TOKEN: ${gitlab_token}" -H "Content-Type: application/json" -d @${tmp_data_file} "http://10.27.249.150:8888/api/v4/projects/${repo_name}/merge_requests" 2>/dev/null)

  # 解析mr请求返回体中error信息
  local msg=$(echo $mr_result | awk -F 'message":' '{print $2}')
  if [ "$msg" != "" ]; then
    local msg2=$(echo $msg | awk -F '401' '{print $2}')
    if [ "$msg2" = "" ]; then
      local msg3=$(echo $msg | awk -F '}' '{print $1}')
      log::info "MR提交失败:"
      log::info "$msg3"
      return 1
    else
      log::info "gitlab token 无效或已过期，请在下行链接获取token"
      log::info "http://10.27.249.150:8888/profile/personal_access_tokens"
      log::info "请使用 ta config GITLAB_TOKEN <token> -g 设置token"
      return 1
    fi
  fi

  local err_cannot_be_merged=$(echo $mr_result | awk -F '"merge_status":"cannot_be_merged"' '{print $2}')
  local err_conflict=$(echo $mr_result | awk -F '"has_conflicts":true' '{print $2}')

  if [ "$err_conflict" != "" ] || [ "$err_cannot_be_merged" != "" ]; then
    log::info "MR已提交，但是有冲突或分支出错，请前往mergeRequest页面查看详情"
    log::info "http://10.27.249.150:8888/${git_repo_group}/${git_repo_project}/merge_requests"
    return 1
  fi

  local msg_can_be_merged=$(echo $mr_result | awk -F '"merge_status":"can_be_merged"' '{print $2}')
  if [ "$msg_can_be_merged" != "" ]; then
    log::info "提交MR成功！"
    log::info "已分配给❤️朱建山❤️进行review"
    return
  fi

  log::info "提交MR成功"

  log::info "日志：$mr_result"
}

export -f ta::mr
