#!/bin/bash

ta::helloworld() {
  echo "helloworld"
}

ta::prepare() {
  # zmicro check version
  local zmicro_version="$(version::zmicro)"
  if [ "$(semver::compare_gte ${zmicro_version} $PLUGIN_TA_ZMICRO_VERSION)" != "true" ]; then
    log::info "[$(timestamp)] zmicro version found update, try to update it ..."
    zmicro update
  fi

  which nvm >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::info "[$(timestamp)] prepare nvm (1) ..."
    zmicro plugin install nvm
  else
    local nvm_bin=$(which nvm)
    local standard_nvm_bin=$ZMICRO_HOME/bin/nvm
    if [ "$nvm_bin" != "$standard_nvm_bin" ]; then
      log::info "[$(timestamp)] prepare nvm (2) ..."
      zmicro plugin install nvm
    fi
  fi

  which node >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] node.js is not installed, try to install it ..."
    nvm use $PLUGIN_TA_NODE_VERSION

    export NODE_HOME=/usr/local/node
    export NODE_USER_HOME=$HOME/.node
    export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH
  fi

  local current_node_version=$(node -v)
  if [ "$current_node_version" != "$PLUGIN_TA_NODE_VERSION" ] && [ "$(version::compare_gt ${current_node_version} $PLUGIN_TA_NODE_VERSION)" = "false" ]; then
    log::info "当前 Node.js 版本是 $(color::red ${current_node_version}), 但是 Ta 系统要求至少 $(color::green ${PLUGIN_TA_NODE_VERSION})"

    if [ "$CI" != "true" ]; then
      os::inquirer value "yesno" "是否确认升级 Node.js 版本 ($(color::green ${PLUGIN_TA_NODE_VERSION}))？" true false
      if [ "$value" != "true" ]; then
        exit 0
      fi
    else
      log::info "CI 环境默认安装 $(color::green ${PLUGIN_TA_NODE_VERSION})"
    fi

    nvm use $PLUGIN_TA_NODE_VERSION
  fi

  which rimraf >>/dev/null
  if [ "$?" != "0" ]; then
    log::info "[$(timestamp)] rimraf is not installed, try to install it ..."
    npm i -g rimraf # --force
  fi

  which gpm >>/dev/null
  if [ "$?" != "0" ]; then
    log::info "[$(timestamp)] gpm is not installed, try to install it ..."
    npm i -g @cliz/gpm # --force
  else
    # check version
    local gpm_version="v$(gpm --version)"
    if [ "$(semver::compare_gte ${gpm_version} $PLUGIN_TA_GPM_VERSION)" != "true" ]; then
      log::info "[$(timestamp)] gpm version found update, try to update it ..."
      npm i -g @cliz/gpm # @$PLUGIN_TA_GPM_VERSION --force
    fi
  fi

  which nrm >>/dev/null
  if [ "$?" != "0" ]; then
    log::info "[$(timestamp)] nrm is not installed, try to install it ..."
    npm i -g @cliz/nrm # --force
  fi
}

export -f ta::helloworld
export -f ta::prepare
