#!/bin/bash

ta::helloworld() {
  echo "helloworld"
}

ta::prepare() {
  which node >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] node.js is not installed, try to install it ..."
    zmicro package install nodejs

    export NODE_HOME=/usr/local/node
    export NODE_USER_HOME=$HOME/.node
    export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH
  fi

  local current_node_version=$(node -v)
  if [ "$current_node_version" != "$PLUGIN_TA_NODE_VERSION" ] && [ "$(version::compare_gt ${current_node_version} $PLUGIN_TA_NODE_VERSION)" = "false" ]; then
    if [ "$CI" != "true" ]; then
      log::info "Your node vrsion is $(color::red ${current_node_version}), but ta system require version at least $(color::green ${PLUGIN_TA_NODE_VERSION})"
      os::inquirer value "yesno" "Are you sure to install node($(color::green ${PLUGIN_TA_NODE_VERSION})) right now ?" true false
      if [ "$value" != "true" ]; then
        exit 0
      fi
    fi

    which nvm >>/dev/null 2>&1
    if [ $? -ne 0 ]; then
      log::info "nvm is not installed, try to install it ..."
      zmicro plugin install nvm
    fi

    nvm use $PLUGIN_TA_NODE_VERSION
  fi

  which rimraf >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] rimraf is not installed, try to install it ..."
    npm i -g rimraf
  fi

  which gpm >>/dev/null
  if [ $? -ne 0 ]; then
    log::info "[$(timestamp)] gpm is not installed, try to install it ..."
    npm i -g gpm
  fi
}

export -f ta::helloworld
export -f ta::prepare
