#!/bin/bash

# commit 提交
ta::sync() {
  local repo_name=$(git::basename)
  local branch=$(git::branch)
  
  if [ "$(ta::should_merge_remote $repo_name $branch)" = "true" ]; then
    ta::merge_remote
    if [ "$?" != "0" ]; then
      return 1
    fi
  fi

  if [ "$no_push" != "true" ]; then
    ta::commit_push
    if [ "$?" != "0" ]; then
      return 1
    fi
  fi
}


export -f ta::sync
