#!/bin/bash

help() {
  echo "GPM - upgrade gpm"
  echo ""
  echo "Usage:"
  echo "  ta upgrade gpm"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::upgrade gpm
}

run() {
  core $@
}

run $@
