#!/bin/bash

help() {
  echo "NODE - upgrade nodejs"
  echo ""
  echo "Usage:"
  echo "  ta upgrade nodejs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::upgrade nodejs
}

run() {
  core $@
}

run $@
