#!/bin/bash

help() {
  echo "NPM - upgrade npm"
  echo ""
  echo "Usage:"
  echo "  ta upgrade npm"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::upgrade npm
}

run() {
  core $@
}

run $@
