#!/bin/bash

help() {
  echo "NRM - upgrade nrm"
  echo ""
  echo "Usage:"
  echo "  ta upgrade nrm"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::upgrade nrm
}

run() {
  core $@
}

run $@
