#!/bin/bash

help() {
  echo "NVM - upgrade nvm"
  echo ""
  echo "Usage:"
  echo "  ta upgrade nvm"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ta::upgrade nvm
}

run() {
  core $@
}

run $@
