#!/bin/bash

help() {
  echo "Build - intl build"
  echo ""
  echo "Usage:"
  echo "  intl build [args...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)] start to build intl ..."

  ta::intl_build
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to build intl"
  fi

  log::info "[$(timestamp)] succeed to build intl."
}

run() {
  core $@
}

run $@
